UserManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_auth.urls'))
]

user_auth/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    
    path('', views.login, name="login"),
    path('signup', views.signup, name="signup"),
    path('profile', views.profile, name="profile"),
    path('get-profile-details', views.get_profile_details, name="get-profile-details"),
    path('upload_page', views.upload_page, name="upload_page"),
    path('upload', views.upload_page, name='upload_page'),
    path('get_all_files', views.get_all_files, name='get_all_files'),

     path('logout', views.user_logout, name='logout'),

] 

user_auth/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserDetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_no = models.CharField(max_length=12, null=True, blank=True)


class UploadedFile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    file = models.FileField(upload_to='uploads/')
    file_type = models.CharField(max_length=100)
    file_size = models.IntegerField()

    def __str__(self):
        return str(self.pk)

user_auth/forms.py
from django import forms
from .models import UploadedFile

class UploadForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ('file',)

    

user_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout
from .models import UserDetails, UploadedFile
from django.contrib import messages
from django.http import JsonResponse
import jwt
from django.conf import settings
from .forms import UploadForm
import os

def generate_jwt_token(user):
    payload = {
        'user_id': user.id,
        'username': user.username,
    }
    token = jwt.encode(payload, settings.SECRET_KEY, algorithm='HS256')
    return {'token': token} 


def login(request):

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = User.objects.filter(email=email).first()
        if user:
            user = authenticate(username=user.username, password=password)
            
            if user:
                token = generate_jwt_token(user)    
                return JsonResponse(token, status=200)  
            else:
                return JsonResponse({'message': 'Invalid email or password'}, status=401)
        else:
            return JsonResponse({'message': 'User does not exist'}, status=404)

    return render(request, 'login.html')


def validate_token(request):
    if request.method == "POST":
        token = request.POST.get('token')
        if token:
            user = validate_jwt_token(token)
            if user:
                return JsonResponse({'message': 'Token is valid'}, status=200)
            else:
                return JsonResponse({'message': 'Invalid token'}, status=401)
        else:
            return JsonResponse({'message': 'Token not provided'}, status=400)
    return JsonResponse({'message': 'Invalid request'}, status=400)


def validate_jwt_token(token):
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=['HS256'])
        user_id = payload['user_id']
        user = User.objects.get(id=user_id)
        return user
    except jwt.ExpiredSignatureError:
        return None
    except (jwt.InvalidTokenError, User.DoesNotExist):
        return None


def profile(request):
    token = request.headers.get('Authorization')
    if token and token.startswith('Bearer '):
        return render(request, 'profile.html')
    else:
        return render(request, 'profile.html', {'error_message': 'Token missing or invalid'})


def get_profile_details(request):
    token = request.headers.get('Authorization')
    if token and token.startswith('Bearer '):
        token = token.split(' ')[1]
        user = validate_jwt_token(token)
        if user:
            full_name = f"{user.first_name} {user.last_name}"
            context = {
                'username': user.username,
                'fullname': full_name,
                'email': user.email
            }
            return JsonResponse(context)
        else:
            return JsonResponse({'error': 'Invalid or expired token'}, status=401)
    else:
        return JsonResponse({'error': 'Authorization token missing or invalid'}, status=401)


def upload_page(request):
    form = UploadForm(request.POST or None, request.FILES or None)
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        token = request.headers.get('Authorization').split(' ')[1]
        file_data = request.FILES.get('file')
        print("Token:", token) 
        user = validate_jwt_token(token)
        if file_data:
            file_extension = os.path.splitext(file_data.name)[1].lower()

            file_size = file_data.size
            print("File size:", file_size, "bytes")

            if file_extension in ['.jpg', '.jpeg', '.png', '.gif']:
                file_type = 'image'
            elif file_extension in ['.mp4', '.avi', '.mov', '.mkv']:
                file_type = 'video'
            elif file_extension in ['.pdf', '.doc', '.docx', '.txt']:
                file_type = 'document'
            else:
                file_type = 'unknown'

            UploadedFile.objects.create(user = user, file=file_data, file_type=file_type, file_size=file_size)

            print("File type:", file_type)
            print("File data:", file_data)

    return render(request, 'file_upload.html')


from django.http import JsonResponse

def get_all_files(request):
    token = request.headers.get('Authorization')
    if token and token.startswith('Bearer '):
        token = token.split(' ')[1]
        user = validate_jwt_token(token)
        if user:
            user_files = UploadedFile.objects.filter(user=user)
            files_data = [
                {
                    'filename': file.file.name[8::],
                    'file_type': file.file_type,
                    'file_size': file.file_size
                }
                for file in user_files
            ]
            return JsonResponse({'files_data': files_data})
        else:
            return JsonResponse({'error': 'Invalid or expired token'}, status=401)
    else:
        return JsonResponse({'error': 'Authorization token missing or invalid'}, status=401)

    
def signup(request):

    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        phoneno = request.POST.get('phoneno')
        
        if not all([username, email, first_name, last_name, password, phoneno]):
            return JsonResponse({'message': 'Please fill in all the fields.'}, status=400)
        
        if User.objects.filter(username=username).exists():
            return JsonResponse({'message': 'Username already exists.'}, status=400)
            
        user = User.objects.create_user(
            username=username,
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        UserDetails.objects.create(user=user, phone_no=phoneno)
        
        messages.success(request, 'Account created successfully. Please login.')
        return JsonResponse({'redirect': '/login'})
    
    return render(request, 'signup.html')


def user_logout(request):
    try:
        print("function si calling::::::::::::::::::")
        if request.user.is_authenticated:
            logout(request)
            return redirect('login')
        else:
            messages.error(request, 'You need to login first')
            return redirect('login')
    except:
        return redirect('login')

templates/file_upload.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>profile</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>    
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-6 col-lg-6 col-xl-6">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body px-5 ">

            <div class="mb-md-5 mt-md-4 pb-5">

                
                <div class="container mt-5 bg-white rounded-lg text-dark p-3">
                    <div id='alert-box'> </div>
                    <br/>
                    <form action='' id="upload-form" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="file" id="id_file" name="file">
                    </form>

                    <div id="progress-box" class="not-visible">
                        progress
                    </div>
                    <div id="cancel-box" class="not-visible" >
                      <button id="cancel-btn" class="btn btn-danger">Cancel</button> 
                    </div>                   
                    <div id="progressBarContainer">
                        <div id="progressBar">
                            <div id="progressBarInner"></div>
                        </div>  
                    </div>
                  </div>
                  <a href={% url 'profile' %}>
                    <button class="btn btn-primary mt-3">back</button> 

                  </a>
    
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</section>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="{% static 'js/upload.js' %}"></script>
    

    
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>    
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body px-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your email and password!</p>

              <form id='login-form' action={% url 'login' %} method="post">
                {% csrf_token %}
                <div class="form-outline form-white mb-4">
                  <label class="form-label">Email</label>
                  <input type="email" id="email" name='email' class="form-control form-control-lg" />
                </div>
  
                <div class="form-outline form-white mb-4">
                  <label class="form-label" >Password</label>
                  <input type="password" id="password" name='password' class="form-control form-control-lg" />
                </div>
                <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>

              </form>
            </div>
            <div>
              <p class="mb-0">Don't have an account? <a href={% url 'signup' %} class="text-white-50 fw-bold">Sign Up</a>
              </p>
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="{% static 'js/login.js' %}"></script>

</body>
</html>

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>profile</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>    
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-12 col-lg-12 col-xl-12">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body px-5 ">

            <div class="mb-md-5 mt-md-4 pb-5">
                <div class="bg-slate-300 w-80 h-80 text-black d-flex flex-row">
                    <!-- User profile image -->
                    <img src="https://picsum.photos/200/200" alt="Profile Image" class="rounded-circle mb-2" style="width: 100px; height: 100px;">
                    <!-- User information -->
                    <div class="row col-12">
                      <div class="col-md-10">
                          <div class="px-3  flex-column">
                            <p class="mb-2 text-black"><span id="profile-username"></p>
                            <p class="mb-2 text-black"><span id="profile-fullname"></p>
                            <p class="mb-2 text-black"><span id="profile-email"></p>
                          </div>
                        </div>
                        <div class="col-md-2">
                        <div class="px-3 flex-column">
                          <a href="{% url 'logout' %}">
                            <button id='logout-button' class="text-white btn btn-primary">Logout</button>
                        </a>
                        
                      </div>
                      
                      </div>
                  </div>
                  
                    
                </div>
                
                <div class="container mt-5 bg-white rounded-lg text-dark">
                  <div class="d-flex justify-content-between mt-2 pt-2">
                    <p class="pt-2 font-medium">Uploaded items</p>
                    <a href={% url 'upload_page' %}><button type="button" class="btn btn-primary mr-1">Upload file</button></a>
                  </div>
                
                


                    <ul class="list-group text-dark ">

                          <span class="float-right"></span>


                    </ul>
                </div>
    
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="{% static 'js/profile.js' %}"> </script>
</body>
</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>    
  <section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-6">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body px-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
                <h2 class="fw-bold mb-2 text-uppercase">Signup</h2>
                <p class="text-white-50 mb-5">Create your account</p>
                <form id='signup-form' action={% url 'signup' %} method='POST'>
                  {% csrf_token %}
                  <div class="d-flex justify-content-between">
                    <div class="form-outline px-2 form-white mb-4">
                      <label class="form-label" for="typeEmailX1">Username</label>
                      <input type="text" id="username" name="username" class="form-control form-control-lg" />
                    </div>
                    <div class="form-outline px-2 form-white mb-4">
                      <label class="form-label" for="typeEmailX2">phone number</label>
                      <input type="phoneno" id="phoneno" name="phoneno" class="form-control form-control-lg" />
                    </div>
                  </div>
  
                  <div class="d-flex justify-content-between">
                    <div class="form-outline px-2 form-white mb-4">
                      <label class="form-label" for="typeEmailX1">First name</label>
                      <input type="text"  id="first_name" name="first_name" class="form-control form-control-lg" />
                    </div>
                    <div class="form-outline px-2 form-white mb-4">
                      <label class="form-label" for="typeEmailX2">Last name</label>
                      <input type="text" id="last_name" name="last_name" class="form-control form-control-lg" />
                    </div>
                  </div>
  
                  <div class="d-flex justify-content-between">
                    <div class="form-outline px-2 form-white mb-4 col-12">
                      <label class="form-label" for="typeEmailX2">Email</label>
                      <input type="email" id="email" name="email" class="form-control form-control-lg" />
                    </div>
                  </div>
  
                  <div class="d-flex justify-content-between">
                    <div class="form-outline px-2 form-white mb-4">
                      <label class="form-label" for="typeEmailX1">Password</label>
                      <input type="password" id="password" name="password" class="form-control form-control-lg" />
                    </div>
                    <div class="form-outline px-2 form-white mb-4">
                      <label class="form-label" for="typeEmailX2">Confirm password</label>
                      <input type="password"  id="confirm_pass" name="confirm_pass" class="form-control form-control-lg" />
                    </div>
                  </div>
                  
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Sign Up</button>
                </form>
                <div>
                  <p class="mb-0 mt-2">Already have an account? <a href="{% url 'login' %}" class="text-white-50 fw-bold">Login</a></p>
                </div>
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>
  
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    
    <script src="{% static 'js/signup.js' %}"> </script>
</body>
</html>